<?php
declare(strict_types=1);

session_start();

require_once __DIR__ . '/config/config.php';
require_once __DIR__ . '/app/services/Router.php';
require_once __DIR__ . '/app/services/Database.php';
require_once __DIR__ . '/app/services/CsrfService.php';
require_once __DIR__ . '/app/services/RateLimiter.php';
require_once __DIR__ . '/app/services/NotificationService.php';
require_once __DIR__ . '/app/services/EventBus.php';
require_once __DIR__ . '/app/services/MatchService.php';
require_once __DIR__ . '/app/services/MessageService.php';
require_once __DIR__ . '/app/services/VipService.php';
require_once __DIR__ . '/app/services/AnalyticsService.php';
require_once __DIR__ . '/app/services/PhotoService.php';
require_once __DIR__ . '/app/controllers/HomeController.php';
require_once __DIR__ . '/app/controllers/AuthController.php';
require_once __DIR__ . '/app/controllers/PushController.php';
require_once __DIR__ . '/app/controllers/NotificationController.php';
require_once __DIR__ . '/app/controllers/SettingsController.php';
require_once __DIR__ . '/app/controllers/EventController.php';
require_once __DIR__ . '/app/controllers/InteractionController.php';
require_once __DIR__ . '/app/controllers/ChatController.php';
require_once __DIR__ . '/app/controllers/VipController.php';
require_once __DIR__ . '/app/controllers/ProfileController.php';
require_once __DIR__ . '/app/controllers/VerificationController.php';
require_once __DIR__ . '/app/controllers/AnalyticsController.php';
require_once __DIR__ . '/app/controllers/PhotoController.php';
require_once __DIR__ . '/app/controllers/PaymentController.php';

$router = new Router();
$router->get('/', [HomeController::class, 'index']);
$router->get('/offline', [HomeController::class, 'offline']);
$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'handleLogin']);
$router->get('/register', [AuthController::class, 'register']);
$router->post('/register', [AuthController::class, 'handleRegister']);
$router->get('/verify', [AuthController::class, 'verify']);
$router->post('/logout', [AuthController::class, 'logout']);
$router->post('/api/push/subscribe', [PushController::class, 'subscribe']);
$router->post('/api/push/unsubscribe', [PushController::class, 'unsubscribe']);
$router->post('/api/events/emit', [EventController::class, 'emit']);
$router->post('/api/react', [InteractionController::class, 'react']);
$router->post('/api/activity/ping', [AnalyticsController::class, 'ping']);
$router->post('/api/payments/webhook', [PaymentController::class, 'webhook']);
$router->get('/notifications', [NotificationController::class, 'index']);
$router->get('/settings/push', [SettingsController::class, 'push']);
$router->post('/settings/push', [SettingsController::class, 'push']);
$router->get('/chat', [ChatController::class, 'show']);
$router->post('/chat/send', [ChatController::class, 'send']);
$router->get('/vip', [VipController::class, 'index']);
$router->post('/vip/trial', [VipController::class, 'startTrial']);
$router->get('/profile', [ProfileController::class, 'index']);
$router->post('/profile/update', [ProfileController::class, 'update']);
$router->post('/profile/photo', [PhotoController::class, 'upload']);
$router->get('/verification', [VerificationController::class, 'index']);
$router->post('/verification/submit', [VerificationController::class, 'submit']);

$router->dispatch($_SERVER['REQUEST_URI']);
